---
- hosts: local
  become: yes
  become_user: root
  connection: local
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: latest
        update_cache: true

    - name: start nginx
      service:
        name: nginx
        enabled: yes
        state: started
